# Generated by Django 5.1.6 on 2025-02-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_schedule_day_of_week_alter_schedule_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='last_taken',
        ),
    ]
