# Generated by Django 5.1.6 on 2025-02-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_medication_last_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='last_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
